import '@/styles/globals.css'
import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { cn } from '@/lib/utils'

import { Inter } from 'next/font/google'
import { Navbar } from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = { children: ReactNode }

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-br" className="h-full">
      <body
        className={cn('h-full relative antialiased font-sans', inter.className)}
      >
        <main className="relative flex flex-col min-h-screen">
          <div className="flex-grow flex-1">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}

export default RootLayout
